services:
  postgres:
    image: postgres:17-alpine
    container_name: assessment-db
    restart: unless-stopped
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: costs
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: costs
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: